name: simple_project
description: "MedStake"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.9.4+5
  flutter_phone_direct_caller: ^2.0.0
  url_launcher: ^6.0.13
  sqflite: ^2.0.0+4
  path: ^1.8.3
  sqflite_common_ffi: ^2.0.0+2
  path_provider: ^2.0.3
  network_info_plus: ^3.0.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.0.1
  file_selector: ^1.0.1
  whatsapp_unilink: ^2.1.0
  contacts_service: ^0.6.3
  fluttertoast: ^8.0.8
  image_picker: ^0.8.4+8
  flutter_tflite: ^1.0.1
  googleapis: ^10.0.0
  video_player: ^2.4.5
  wifi_iot: ^0.3.12
  googleapis_auth: ^1.4.0
  http: ^0.13.0
  font_awesome_flutter: ^10.0.0
  intl: ^0.17.0
  encrypt: ^5.0.0
  webview_flutter: ^3.0.0
  webview_flutter_plus: ^0.3.0+2
  flutter_local_notifications: ^13.0.0
  timezone: ^0.9.4
  firebase_core: ^2.4.0
  firebase_messaging: ^14.0.0
  google_sign_in: ^5.4.2
  flutter_web_auth: 0.5.0
  flutter_appauth: ^1.1.0
  get: ^4.6.5
  flutter_rating_bar: ^4.0.1
  animations: ^2.0.3
  flutter_round_slider: ^1.0.0
  sleek_circular_slider: ^2.0.1
  floating_frosted_bottom_bar: ^0.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/telemedicine.png"  # Path to your main icon

flutter:
  uses-material-design: true

  assets:
    - assets/advice.png
    - assets/diagnose.png
    - assets/medical.png
    - assets/viewImages.png
    - assets/telemedicine.png
    - assets/zoom.jpg
    - assets/googleMeet.png
    - assets/googleMeetIcon.jpeg
    - assets/model_unquant.tflite
    - assets/labels.txt
    - assets/stake.png
    - assets/microsoftTeams.jpg
    - assets/meet.gif
    - assets/pills.png
    - assets/ndandi.jpg
    - assets/fb.png
    - assets/google.png
    - assets/doctor6.png
    - assets/doctor3.png