name: simple_project
description: "Health Application"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.9.4+5

  flutter_phone_direct_caller: ^2.0.0
  url_launcher: ^6.0.13
  sqflite: ^2.0.0+4
  path: ^1.8.3
  sqflite_common_ffi: ^2.0.0+2
  path_provider: ^2.0.3
  network_info_plus: ^3.0.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.0.1
  file_selector: ^1.0.1
  whatsapp_unilink: ^2.1.0
  contacts_service: ^0.6.3
  fluttertoast: ^8.0.8
  image_picker: ^0.8.4+8
  flutter_tflite: ^1.0.1
  http: ^0.13.4
  video_player: ^2.4.5
  wifi_iot: ^0.3.12
  font_awesome_flutter: ^10.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/greenIcon.jpg"  # Path to your main icon

flutter:
  uses-material-design: true

  assets:
    - assets/advice.png
    - assets/diagnose.png
    - assets/medical.png
    - assets/viewImages.png
    - assets/telemedicine.png
    - assets/zoom.jpg
    - assets/model_unquant.tflite
    - assets/labels.txt